Catalogue.web/Models/ErrorViewModel.cs
namespace Catalogue.web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Catalogue.web/Models/LoginModel.cs
namespace Catalogue.web.Models
{
    public class LoginModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public bool RemenberMe { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Catalogue.web/Models/SalleModel.cs
namespace Catalogue.web.Models
{
    public class SalleModel
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public string Libelle { get; set;}
        public string Description { get; set;}
        public string Picture { get; set; }
        public Boolean isReserve { get; set; }
        public SalleModel() { }
        public SalleModel(int id, string numero, string libelle, string description, string picture, bool isReserve)
        {
            Id = id;
            Numero = numero;
            Libelle = libelle;
            Description = description;
            Picture = picture;
            this.isReserve = isReserve;
        }
    }
}

Catalogue.web/Models/UserModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Catalogue.web.Models
{
    public class UserModel
    {
       
            public int Id { get; set; }
            public string Username { get; set; }
            public string Password { get; set; }
            public DateTime CreatedAt { get; set; }
            public string Profile { get; set; }
            public string Picture { get; set; }
            public IEnumerable<SelectListItem> Profiles { get; set; }
            public int ProfilesSelectValue { get; set; }


            public UserModel()
            {

            }

            public UserModel(int id, string username, string password, DateTime createdAt, string profile, string picture)
            {
                Id = id;
                Username = username;
                Password = password;
                CreatedAt = createdAt;
                Profile = profile;
                Picture = picture;
            }

            public UserModel(int id, string username, string password, DateTime createdAt, string profile, string picture, IEnumerable<SelectListItem> profiles) : this(id, username, password, createdAt, profile, picture)
            {
                Profiles = profiles;
            }
        }
    
}

Catalogue.web/Controllers/AccountController.cs
using Catalogue.web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Catalogue.web.Controllers
{
    public class AccountController : Controller
    {
        public ActionResult Index(string returnUrl = null)
        {
            var model = new LoginModel { ReturnUrl = returnUrl };
            return View(model);
        }

        public ActionResult Login()
        {

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            try
            {
             
                return RedirectToAction("Index", "Home");
            }
            catch (KeyNotFoundException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (UnauthorizedAccessException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occured. please try again later !");

                Console.Error.WriteLine($"---> {ex.Message} ");
            }

            return View("Index", model);
        }
    }
}

Catalogue.web/Controllers/CreatedController.cs
using Catalogue.web.Models;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace Catalogue.web.Controllers
{
    public class CreatedController : Controller
    {
        public List<SalleModel> salles;
        public CreatedController()
        {

            salles = new List<SalleModel>(){   new SalleModel(1, "AC023", "salle de conference", "rien a signaler", "./images/salle1.jpg", true),
            new SalleModel(1, "yoyooy", "totototo", "roror", "./images/salle3.jpg", false)};
        }
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult CreateSalle(SalleModel salleModel)
        {
            salles.Add(new SalleModel(salleModel.Id, salleModel.Numero, salleModel.Libelle, salleModel.Description, salleModel.Picture, false));
            return RedirectToAction("Index", "Home", salles);
        }
    }
}

Catalogue.web/Controllers/HomeController.cs
using Catalogue.web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Catalogue.web.Controllers
{
   
    public class HomeController : Controller
    {

        public List<SalleModel> salles;
        public HomeController()
        {
            salles = new List<SalleModel>(){
            new SalleModel(1, "AC023", "salle de conference", "rien a signaler", "./images/salle1.jpg", true),
            new SalleModel(1, "CH044", "amphis 150", "roror", "./images/salle2.jpg", false),
            new SalleModel(1, "CE059", "salle de conference 2", "roror", "./images/salle3.jpg", false),
            new SalleModel(1, "CF590", "salle de cour commun", "roror", "./images/salle4.jpg", false),
            new SalleModel(1, "AD390", "salle informatique", "roror", "./images/salle5.jpg", false),
            new SalleModel(1, "AJ033", "salle de fete", "roror", "./images/salle6.jpg", true),
            };
            
        }

        public ActionResult Index()
        {

            return View(salles);
        }

        public ActionResult Privacy()
        {
            return View();
        }

       
    }
}

Catalogue.web/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Catalogue.web.Controllers
{
    public class ReservationController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Catalogue.web/Views/Created/Index.cshtml
@model Catalogue.web.Models.LoginModel

@{
    Layout = null;
}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Connexion</title>
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/all.min.css" />
</head>
<body class=" h-screen w-screen bg-blue-50 overflow-hidden">
    <h1 class="text-center text-xl pt-5">create and manager <span class="text-[32px] border-0 text-bold text-blue-500">teacher, classroom and lesson</span></h1>
    

    <div class="flex justify-around w-screen items-center  h-screen ">
        
        <div class="flex flex-col items-center space-y-4 shadow-xl rounded-xl m-auto">
            <div class="h-[50%] bg-blue-50 px-5 pt-5">
                <div class="flex items-center space-x-2 text-purple-500">
                    <div class="w-[40px] h-[40px] rounded-full bg-purple-500 flex items-center justify-center  ">
                        <i class="fa fa-door-open text-white"></i>
                    </div>
                    <span>Classroom</span>
                    
                </div>
                <p>create any teacher from your system!</p>
            </div>
            <input type="text" class="w-[90%] py-1 pl-2" placeholder="numero de la salle" />
            <input type="text" class="w-[90%] py-1 pl-2" placeholder="libelle de la salle" />
            <textarea class="w-[90%] h-[50px]"></textarea>
           
            <div class="bg-white w-full flex flex-col items-center px-5 pb-5">
                <div class="relative w-[90%] h-[100px] flex flex-col items-center justify-center border border-dotted border-purple-500">
                    <input type="file" class=" absolute cursor-pointer opacity-0 w-[90%] h-[100px]" />
                    <i class="fa fa-upload  text-purple-500"></i>
                    <span class="text-gray-500 text-sm">upload image</span>
                </div>
                <span class="text-sm text-gray-500 p-3">the teacher is a standart user to the plateform</span>
                <a href="@Url.Action("Index", "Home")" class="px-12 py-1 border border-2 cursor-pointer border-green-500 text-green-400 rounded-lg">
                    Create
                </a>
            </div>


        </div>
        <div class="flex flex-col items-center space-y-4 shadow-xl rounded-xl m-auto">
            <div class="h-[50%] bg-blue-50 px-5 pt-5">
                <div class="flex items-center space-x-2 text-orange-500">
                    <div class="w-[40px] h-[40px] rounded-full bg-orange-500 flex items-center justify-center  ">
                        <i class="fa fa-book text-white"></i>
                    </div>
                    <span>lesson</span>

                </div>
                <p>create any teacher from your system!</p>
            </div>
            <div class="bg-white w-full flex flex-col items-center px-5 pb-5">
                <span class="text-sm text-gray-500 p-3">the teacher is a standart user to the plateform</span>
                <a class="px-12 py-1 border border-2 cursor-pointer border-green-500 text-green-400 rounded-lg">
                    Create
                </a>
            </div>


        </div>
        <div class="flex flex-col items-center space-y-4 shadow-xl rounded-xl m-auto">
            <div class="h-[50%] bg-blue-50 px-5 pt-5">
                <div class="flex items-center space-x-2 text-black">
                    <div class="w-[40px] h-[40px] rounded-full bg-black flex items-center justify-center  ">
                        <i class="fa fa-user text-white"></i>
                    </div>
                    <span>Teacher</span>

                </div>
                <p>create any teacher from your system!</p>
                
            </div>
            <div class="relative w-[60px] h-[60px] flex flex-col rounded-full items-center justify-center border border-dotted border-black">
                <input type="file" class=" absolute cursor-pointer opacity-0 w-[90%] h-[100px]" />
                <i class="fa fa-user  text-purple-500"></i>
            </div>
            <input type="text" class="w-[90%] py-1 pl-2" placeholder="matricule enseigant" />
             <input type="text" class="w-[90%] py-1 pl-2" placeholder="email de l'enseignant'" />
            <input type="text" class="w-[90%] py-1 pl-2" placeholder="mot de passe" />
            <input type="password" class="w-[90%] py-1 pl-2" placeholder="matiere a dispenser" />
            <div class="bg-white w-full flex flex-col items-center px-5 pb-5">
                <span class="text-sm text-gray-500 p-3">the teacher is a standart user to the plateform</span>
                <a href="@Url.Action("Index", "Home")" class="px-12 py-1 border border-2 cursor-pointer border-green-500 text-green-400 rounded-lg">
                    Create
                </a>
            </div>


        </div>
       

    </div>

</body>
</html>

Catalogue.web/Views/Home/Index.cshtml
@model IEnumerable<Catalogue.web.Models.SalleModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="flex">
    <div class="p-3 flex flex-col space-y-4 border-r">
        <div class="flex">
            <div class="flex flex-1 space-x-2 items-center">
                <img src="./images/user1.jpg" alt="" class="rounded-full" width="50" />
                <div class="flex flex-col">
                    <span class="font-bold text-lg">
                        Tony Monata
                    </span>
                    <span class="text-xs">scarface</span>
                </div>
            </div>
            <a href="@Url.Action("Index", "Created")" class="w-[40px] h-[40px] rounded-full cursor flex justify-center items-center bg-green-500">
                <i class="fa fa-plus text-white font-bold"></i>
            </a>
        </div>
        
        <div class="flex space-x-4 border-b pb-4 border-gray-100">
            <div class="flex items-center space-x-2">
                <div class="rounded-full bg-gray-200 w-[25px] h-[25px] flex justify-center items-center" ><i class="fa fa-sun"></i></div>
                <div class="flex flex-col">
                    <span class="font-bold text-lg">257</span>
                    <span class="text-xs font-light">students</span>
                </div>
            </div>
            <div class="flex items-center space-x-2">
                <div class="rounded-full bg-gray-200 w-[25px] h-[25px] flex justify-center items-center"><i class="fa fa-fan"></i></div>
                <div class="flex flex-col">
                    <span class="font-bold text-lg">31</span>
                    <span class="text-xs font-light">teachers</span>
                </div>
            </div>
        </div>
        <div class="space-y-4">
            <div class="flex space-x-2 items-center">
                <span class="text-xl font-bold">Recomended</span>
                <span class="w-[25px] h-[25px] flex justify-center items-center rounded-full text-sm bg-gray-200">@Model.Count()</span>
            </div>
            <div class="overflow-y-scroll h-auto  ">
                <div class="space-y-8 h-[400px]">
                    @if (Model != null && Model.Count() > 0)
                    {
                        foreach (var salle in Model)
                        {
                            <div class="flex flex-col p-2 rounded-xl bg-green-200 cursor-pointer relative ">
                               
                                <img src=@salle.Picture width="400" class="rounded-lg hover:scale-110" />
                                <div class="flex space-x-6 p-1 justify-between items-center">
                                    <span class=" w-[200px] lending-0 font-bold">@salle.Libelle</span>
                                    <div class="flex space-x-4">
                                        <span class="text-xs"><i class="fa fa-clock"></i>10min</span>
                                        <span class="text-xs">@salle.Numero cal</span>
                                    </div>
                                   
                                </div>
                               
                                <div class="flex items-center justify-between">
                                    <div class="relative w-[150px] h-[30px]">
                                        <img src="./images/user1.jpg" width="25" class="rounded-full absolute" />
                                        <img src="./images/user2.jpg" width="25" class="rounded-full absolute left-4" />
                                        <img src="./images/user3.jpg" width="25" class="rounded-full absolute left-8" />
                                       
                                    </div>
                                    @if (!salle.isReserve)
                                    {
                                        <a href="@Url.Action("Index", "Reservation")" class="text-sm text-white px-10 rounded-full z-20 py-1 border-2 border-white">
                                            reserver
                                        </a>
                                    }
                                    
                                </div>
                            </div>
                        }
                    }
                    
                    <div class="flex flex-col p-2 rounded-xl bg-red-200 cursor-pointer relative ">
                        <img src="./images/salle2.jpg" width="400" class="rounded-lg hover:scale-105 hover:transition-all duration-5" />
                        <span class=" w-[200px] ">The 10-minutes ultimate legs workout</span>
                        <div class="flex items-center justify-between">
                            <div class="relative w-[150px] h-[30px]">
                                <img src="./images/user1.jpg" width="25" class="rounded-full absolute" />
                                <img src="./images/user2.jpg" width="25" class="rounded-full absolute left-4" />
                                <img src="./images/user3.jpg" width="25" class="rounded-full absolute left-8" />

                            </div>

                            <div class="flex space-x-4">
                                <span class="text-xs"><i class="fa fa-clock"></i>10min</span>
                                <span class="text-xs">AS605 cal</span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            
        </div>
    </div>
    <div class="p-3 flex flex-col space-y-4 border-r">
         <div class="flex items-center">
             <span class="text-xl flex-1">Cours</span>
             <span class="border-2 px-6 py-1 rounded-full">In Progress</span>
         </div>
         <div class="flex space-x-2 items-start">
            <span class="w-[40px] h-[40px] text-white  rounded-full bg-black flex items-center justify-center">
                <i class="fa fa-user"></i>
             </span>
             <div class="border-2 border-gray-200  flex flex-col w-[350px] cursor-pointer p-3 rounded-xl">
                 <div class="flex justify-between mb-3">
                    <span class="px-2 py-1 rounded-full bg-gray-200 text-xs">1/2</span>
                    <span class="w-[20px] h-[20px] rounded-full bg-gray-200 flex items-center justify-center"><i class="fa fa-circle-ellipsis"></i></span>
                 </div>
                 <span class="text-xs text-gray-500">Cour de programmation Oriente objet</span>
                 <p class="w-[250px] mb-1">Ce cour est pour les etudiants de premiere annee en genie logiciel</p>
                 <div class="border-2 rounded-1 mb-1">
                 </div>
                 <div class="flex items-center justify-between">
                     <span class="text-gray-500 text-xs">20 Feb,23</span>
                    <span class="text-gray-500 text-xs">23 Mar,23</span>
                 </div>
             </div>
         </div>
        <div class="flex space-x-2 items-start">
            <span class="w-[40px] h-[40px]  rounded-full bg-pink-400 flex items-center justify-center">
                <i class="fa fa-user"></i>
            </span>
            <div class="border-2 border-gray-200  flex flex-col w-[350px] cursor-pointer p-3 rounded-xl">
                <div class="flex justify-between mb-3">
                    <span class="px-2 py-1 rounded-full bg-gray-200 text-xs">1/2</span>
                    <span class="w-[20px] h-[20px] rounded-full bg-gray-200 flex items-center justify-center"><i class="fa fa-circle-ellipsis"></i></span>
                </div>
                <span class="text-xs text-gray-500">Cour de programmation Oriente objet</span>
                <p class="w-[250px] mb-1">Ce cour est pour les etudiants de premiere annee en genie logiciel</p>
                <div class="border-2 rounded-1 mb-1">
                </div>
                <div class="flex items-center justify-between">
                    <span class="text-gray-500 text-xs">20 Feb,23</span>
                    <span class="text-gray-500 text-xs">23 Mar,23</span>
                </div>
            </div>
        </div>
        <div class="flex space-x-2 items-start">
            <span class="w-[40px] h-[40px]  rounded-full bg-yellow-400 flex items-center justify-center">
                <i class="fa fa-user"></i>
            </span>
             <div class="border-2 border-gray-200  flex flex-col w-[350px] cursor-pointer p-3 rounded-xl">
                 <div class="flex justify-between mb-3">
                    <span class="px-2 py-1 rounded-full bg-gray-200 text-xs">2/2</span>
                    <span class="w-[20px] h-[20px] rounded-full bg-gray-200 flex items-center justify-center"><i class="fa fa-circle-ellipsis"></i></span>
                 </div>
                 <span class="text-xs text-gray-500">Series of nutrition lecture</span>
                 <p class="w-[250px] mb-1">Dietary ntriens associated with short and long sleep duration</p>
                 <div class="border-2 rounded-1 mb-1">
                 </div>
                 <div class="flex items-center justify-between">
                    <span class="text-gray-500 text-xs">20 Feb,23</span>
                    <span class="text-gray-500 text-xs">20 Dec,22</span>
                 </div>
             </div>
         </div>
        

    </div>
    <div class="p-3 flex flex-col space-y-4 flex-1">
        <div class="flex justify-between items-center">
            <span class="text-bold text-xl">Today shuldle</span>
            <div class="flex space-x-2">
                <div class="w-[20px] h-[20px] rounded-full bg-gray-200 flex justify-center items-center">
                    <i class="fa fa-arrow-left"></i>
                </div>
                <div class="w-[20px] h-[20px] rounded-full bg-gray-200 flex justify-center items-center">
                    <i class="fa fa-arrow-right"></i>
                </div>
            </div>
        </div>
        <div class="flex items-center space-x-3">
            <div class="border-1 border flex-1 relative">
            </div>
            <span class="text-gray-500 text-sm">09h:00</span>
        </div>
       
        <div class="bg-purple-200 flex flex-col p-3 rounded-xl">
            <div class="flex items-center mb-3">
                <div class="flex space-x-2 flex-1">
                    <div class="px-4 py-1 bg-white rounded-xl">
                        09h:30 - 12h:30
                    </div>
                    <div class="w-[30px] h-[30px] rounded-full bg-white flex justify-center items-center">
                        <div class="w-[20px] h-[20px] rounded-full bg-gray-200 bg-purple-200 flex justify-center items-center">
                            <i class="fa fa-check"></i>
                        </div>
                    </div>
                </div>
                <div class="w-[25px] h-[25px] rounded-full bg-gray-200 flex justify-center items-center">

                </div>
            </div>
            <span class="text-sm text-gray-500">routine with time Reddish</span>
            <h1 class="font-semiBold">the upper-body workout</h1>
        </div>
        <div class="flex items-center space-x-3">
            <div class="border-1 border flex-1 relative">
            </div>
            <span class="text-gray-500 text-sm">15h:00</span>
        </div>
        <div class="bg-purple-200 flex flex-col p-3 rounded-xl">
            <div class="flex items-center mb-3">
                <div class="flex space-x-2 flex-1">
                    <div class="px-4 py-1 bg-white rounded-xl">
                        15h:30 - 16h:30
                    </div>
                    <div class="w-[30px] h-[30px] rounded-full bg-white flex justify-center items-center">
                        <div class="w-[20px] h-[20px] rounded-full bg-gray-200 bg-purple-200 flex justify-center items-center">
                            <i class="fa fa-check"></i>
                        </div>
                    </div>
                </div>
                <div class="w-[25px] h-[25px] rounded-full bg-green-500 flex justify-center items-center">
                </div>
            </div>
            <span class="text-sm text-gray-500">routine with time Reddish</span>
            <h1 class="font-semiBold">the upper-body workout</h1>
        </div>
         <div class="flex items-center space-x-3">
            <div class="border-1 border flex-1 relative">
            </div>
            <span class="text-gray-500 text-sm">17h:00</span>
        </div>

        <div class="bg-purple-200 flex flex-col p-3 rounded-xl">
            <div class="flex items-center mb-3">
                <div class="flex space-x-2 flex-1">
                    <div class="px-4 py-1 bg-white rounded-xl">
                        17h:30 - 21h:00
                    </div>
                    <div class="w-[30px] h-[30px] rounded-full bg-white flex justify-center items-center">
                        <div class="w-[20px] h-[20px] rounded-full bg-gray-200 bg-purple-200 flex justify-center items-center">
                            <i class="fa fa-check"></i>
                        </div>
                    </div>
                </div>
                <div class="w-[25px] h-[25px] rounded-full bg-green-500 flex justify-center items-center">

                </div>
            </div>
            <span class="text-sm text-gray-500">routine with time Reddish</span>
            <h1 class="font-semiBold">the upper-body workout</h1>
        </div>
        <div class="flex items-center space-x-3">
            <div class="border-1 border flex-1 relative">
            </div>
            <span class="text-gray-500 text-sm">21h:00</span>
        </div>
    </div>
</div>

Catalogue.web/Views/Reservation/Index.cshtml
@model Catalogue.web.Models.LoginModel

@{
    Layout = "~/views/shared/_Layout.cshtml";
}


    <div class="bg-blue-50 p-0 m-0">
        <div class="flex justify-between p-3">
            <div class="w-full items-center px-2 flex-col py-4 rounded-xl bg-white">
                <p>salle AI203</p>
                <p class="font-bold text-xl ">salle de conference</p>
            </div>
        </div>
        <div class="flex justify-around items-center">
            <div class="w-[500px] h-[300px] flex justify-center items-center rounded-full bg-white m-auto">
                <img src="~/images/salle1.jpg" width="400px" class="h-auto rounded-full cursor-pointer hover:scale-110" />
            </div>
            <div class="flex flex-col p-3 space-y-4 shadow-xl rounded-xl m-auto">
                <div class="h-[50%] bg-blue-50 px-5 pt-5">
                    <div class="flex items-center space-x-2 text-purple-500">
                        <div class="w-[40px] h-[40px] rounded-full bg-purple-500 flex items-center justify-center  ">
                            <i class="fa fa-door-open text-white"></i>
                        </div>
                        <span>reservation</span>
                    </div>
                    <p>faites vos reservation ici!</p>
                </div>
                <input type="text" class="w-full py-1 pl-2" placeholder="matiere a dispence" />
                <span class="text-sm text-gray-500">date debut</span>
                <input type="datetime-local" class="w-full py-1 pl-2" placeholder="date debut" />
                <span class="text-sm text-gray-500">date fin</span>
                <input type="datetime-local" class="w-full py-1 pl-2" placeholder="date fin" />
                <textarea class="w-full h-[80px]"></textarea>

                <div class="bg-white w-full flex flex-col items-center px-5 pb-5">
                    <span class="text-sm text-gray-500 p-3">the teacher is a standart user to the plateform</span>
                    <a href="@Url.Action("Index", "Home")" class="px-24 bg-green-500 py-2 border-0 cursor-pointer font-bold text-white rounded-lg">
                        Reserver maintenant
                    </a>
                </div>


            </div>
        </div>


    </div>

Catalogue.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Catalogue.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css"  />
    <link rel="stylesheet" href="~/css/all.min.css"  />
    <link rel="stylesheet" href="~/css/style.css"  />
   
  
</head>
<body class="h-screen w-full">
  <header class="flex items-center border p-2 border-black">
       <img src="~/images/logo.png" alt="" class="mr-8"  width="150" />
      <div class=" flex space-x-6 flex-1">
            <a href=""> Home&nbsp;<i class="fa fa-home"></i></a>
            <a href="">Workout&nbsp;<i class="fa fa-car"></i></a>
            <a href="">Learn&nbsp;<i class="fa fa-school"></i></a>
            <a href="">Hub&nbsp;<i class="fa-brands fa-github"></i></a>
            <a href="">Activity&nbsp;<i class="fa fa-chart-line"></i></a>
            <a href="">Leaderboard&nbsp;<i class="fa fa-cash-register"></i></a>
            <a href="">Community&nbsp;<i class="fa fa-satellite-dish"></i></a>
            <a href="">FAQ&nbsp;<i class="fa fa-question"></i></a>
      </div>
      <div>
          <div class="w-[40px] h-[40px] flex justify-center items-center rounded-full bg-gray-700">
                <i class="fa-solid fa-user text-white"></i>
          </div>
      </div>
  </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
       
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>